name: Build EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # 降級到 Python 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.3.1  # 移除 +cpu 後綴
        pip install -r novel/requirements.txt
        pip install pyinstaller
    
    - name: Build EXE
      run: pyinstaller --onefile novel/novel.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: novel_app
        path: dist/novel.exe
